### ISSUE TITLE
The menu of DPI/resolutions should indicate which menu item is effective

### ISSUE THREAD

**Issue by grahamperrin** [trueos/pcdm#5]
Enhancement request, complementary to #1 

There should be a tick/checkmark against whatever is active. 

Without that mark: sometimes when I see the menu, I don't intuitively know whether I'm 'at' medium and need to go 'lower'; or whether I'm at something other than medium and need to switch to medium.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-core#76
