### ISSUE TITLE
Regression: PCDM allows PersonaCrypt users to log in without entry of the pass phrase for GELI

### ISSUE THREAD

**Issue by grahamperrin** [trueos/pcdm#6]
Bug: password for GELI not required. 

The result is an empty home directory, which can be disconcerting.

**Comment by grahamperrin** [comment]
https://github.com/trueos/pcbsd/commit/8098d5817b515bc370f944fc17a4304a8678f072 but then, https://bugs.pcbsd.org/issues/14541#note-5

> I have the same problem (the same symptom) with 11.0-CURRENTJUNE2016.
> 
> A regression?

– and https://bugs.pcbsd.org/issues/14541#note-7

> Seems fixed in TrueOS

**Comment by beanpole135** [comment]
Fixed in the version of PCDM used by TrueOS.
I added a little GUI-side password input verification logic so it only activates the login button if there is something entered into the password box(es).

https://github.com/trueos/pcdm/commit/2cec451309cb15302058ce2b479383be91b7c1b1
